apiVersion: v1
kind: ConfigMap
metadata:
 name: nginx-html
data:
 index.html: |
   <!DOCTYPE html>
   <html>
   <head>
       <title>GitOps Demo</title>
   </head>
   <body>
       <h1>GitOps Update  Successful using argocd</h1>
       <p>Served from ConfigMap</p>
       <p>Version 2</p>
   </body>
   </html>
